226056 added the ability to parse GML.MultiGeometry
Flexberry/Leaflet-WFST pull request #109
Opened 2023-01-20 10:12 UTC by viatkinviatkin

- Added MultiGeometry parser
- Extended responseToLayers for array nodes
- Refactored AbstractMultiGeometry heirs

2023-01-25 18:30 UTC, kuzkok requested changes

2023-01-25 18:30 UTC, kuzkok commented on src/Format/Parsers/Layers/AbstractMultiGeometry.js
> + * @class GML.MultiGeometry
Не соответствует классу

2023-01-25 18:30 UTC, kuzkok commented on src/Format/Parsers/Layers/AbstractMultiPolygon.js
> +    var latLngs = L.GML.AbstractMultiGeometry.prototype.transform.call(this, coordinates, options);
а зачем тут вызов через базовый класс? L.GML.AbstractMultiGeometry.prototype.parse надо вызывать т.к. это аналог _super(...arguments) из эмбера, а в случае с transform достаточно this.transform(coordinates, options) и так оно не выпадет из стилистики остальных классов

2023-01-25 18:30 UTC, kuzkok commented on src/Format/Format.GML.js
> +      Array.from(featureMembersNodes).forEach(function (featureMembersNode) {
featureMembers может быть только один, не надо тут forEach, вот xsd из стандарта
![image](https://user-images.githubusercontent.com/829195/214651288-f32a8414-4962-4528-8c6d-c6b43cd69e5c.png)

2023-01-26 05:59 UTC, viatkinviatkin commented on src/Format/Parsers/Layers/AbstractMultiGeometry.js
> + * @class GML.MultiGeometry
Исправил на AbstractMultiGeometry

2023-01-26 06:01 UTC, viatkinviatkin commented on src/Format/Parsers/Layers/AbstractMultiPolygon.js
> +    var latLngs = L.GML.AbstractMultiGeometry.prototype.transform.call(this, coordinates, options);
Исправил на this.transform(coordinates, options) из дочерних

2023-01-26 06:01 UTC, viatkinviatkin commented on src/Format/Format.GML.js
> +      Array.from(featureMembersNodes).forEach(function (featureMembersNode) {
Исправил на featureMembersNode[0]

2023-01-26 10:16 UTC, kuzkok reviewed
Ещё форматирование местами поехало - то пробела не хватает, то отступы не те

2023-01-26 10:16 UTC, kuzkok commented on spec/Format/Parsers/AbstractMultiPolygon.js
> +    //stub.restore();
комментарий убрать, и надо ещё добавить expect для latlngs - какие они должны быть

2023-01-26 10:16 UTC, kuzkok commented on spec/Format/Parsers/AbstractMultiPolyline.js
>      expect(result).to.be.instanceOf(L.Polyline);
тоже добавить expect на latlngs

2023-01-26 10:16 UTC, kuzkok commented on src/Format/Format.GML.js
> +        }
а тут прям остановить надо или можно только вот эту конкретную фичу не обрабатывать, а остальные должны появиться?

2023-01-26 10:19 UTC, viatkinviatkin commented on spec/Format/Parsers/AbstractMultiPolygon.js
> +    //stub.restore();
Коммент убрал

2023-01-26 10:19 UTC, viatkinviatkin commented on src/Format/Format.GML.js
> +        }
Прописал continue;

2023-01-26 10:44 UTC, viatkinviatkin commented on spec/Format/Parsers/AbstractMultiPolyline.js
>      expect(result).to.be.instanceOf(L.Polyline);
Добавил

2023-01-27 09:43 UTC, kuzkok approved these changes

2023-01-31 12:12 UTC, merged