multipoint
Flexberry/Leaflet-WFST pull request #110
Opened 2023-02-22 13:09 UTC by DaryaNeko

2023-02-22 13:13 UTC, kuzkok requested changes

2023-02-22 13:13 UTC, kuzkok commented on src/GML/FeatureGroup.js
> +        }
выглядит лишним, если это featureGroup с точкой - то это всегда мультиточка, 
forceMulti был актуален для полигонов и полилиний которые могут быть как мульти так и нет.

2023-02-22 13:13 UTC, kuzkok commented on src/GML/FeatureGroup.js
> +    toGml: function (crs, forceMulti) {
тест хорошо бы написать.

2023-02-22 15:54 UTC, DaryaNeko commented on src/GML/FeatureGroup.js
> +        }
убрала

2023-02-25 10:07 UTC, DaryaNeko commented on src/GML/FeatureGroup.js
> +    toGml: function (crs, forceMulti) {
Готово

2023-02-27 06:25 UTC, merged